spring:
  config:
    import: configserver:http://localhost:9000
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/minifin
      username: user
      password: qwer1234
  jpa:
    open-in-view: false
    properties:
      alect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
  application:
    name: review-service
server:
  port: 9510

