eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  config:
    import: configserver:http://localhost:9000
  cloud:
    gateway:
      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/items/**
            - Path=/item/**
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/reviews/**
            - Path=/review/**
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/members/**
            - Path=/member/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
            - Path=/order/**
        - id: mypage-service
          uri: lb://mypage-service
          predicates:
            - Path=/mypage/**